#!/bin/bash
# update-checksums.sh
# Computes SHA-256 checksums for every source file listed in RE_AGENTS_CONFIG.md
# and writes results to artifacts/source_checksums.governance.md.
#
# Run this before starting or resuming a pipeline session to ensure
# analysis-planner can detect which source files have changed since the last run.
#
# Usage:
#   bash pipeline/scripts/update-checksums.sh
#
# Requires: sha256sum (Linux) or shasum -a 256 (macOS)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CONFIG_FILE="$REPO_ROOT/RE_AGENTS_CONFIG.md"
OUTPUT_FILE="$REPO_ROOT/artifacts/source_checksums.governance.md"
PREV_FILE="$REPO_ROOT/artifacts/source_checksums_prev.governance.md"
DATE="$(date +%Y-%m-%d)"

echo ""
echo "RE Agent Pack — Source Checksum Update"
echo "======================================="
echo ""

# Verify config exists
if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "ERROR: RE_AGENTS_CONFIG.md not found at $REPO_ROOT"
    echo "Run the project-scanner agent (Step 0) first."
    exit 1
fi

# Detect sha256sum vs shasum (macOS)
if command -v sha256sum &>/dev/null; then
    SHA_CMD="sha256sum"
elif command -v shasum &>/dev/null; then
    SHA_CMD="shasum -a 256"
else
    echo "ERROR: Neither sha256sum nor shasum found. Cannot compute checksums."
    exit 1
fi

# Extract source file paths from the All Source Files section of RE_AGENTS_CONFIG.md
# Handles two formats:
#   "  - filepath"   (list-marker style)
#   "  filepath"     (plain-indented style, no dash)
# Both are valid outputs from project-scanner.
SOURCE_FILES=()
in_section=false
in_files_list=false
while IFS= read -r line; do
    if [[ "$line" =~ ^##\ Source\ Location ]]; then
        in_section=true
        continue
    fi
    if [[ "$in_section" == true && "$line" =~ ^##[[:space:]] ]]; then
        # Hit the next section — stop
        in_section=false
        in_files_list=false
        continue
    fi
    # Detect the "All Source Files:" label line — everything after it is a file path
    if [[ "$in_section" == true && "$line" =~ \*\*All\ Source\ Files ]]; then
        in_files_list=true
        continue
    fi
    if [[ "$in_files_list" == true ]]; then
        # Trim leading whitespace
        trimmed="${line#"${line%%[! ]*}"}"
        # Strip optional leading "- " (list-marker style)
        trimmed="${trimmed#- }"
        # Strip Windows carriage returns
        trimmed="${trimmed//$'\r'/}"
        # Skip blank lines, bold field labels (**), markdown blockquotes (>), and HR separators (---)
        if [[ -z "$trimmed" || "$trimmed" =~ ^\*\* || "$trimmed" =~ ^\> || "$trimmed" =~ ^--- ]]; then
            continue
        fi
        SOURCE_FILES+=("$trimmed")
    fi
done < "$CONFIG_FILE"

if [[ ${#SOURCE_FILES[@]} -eq 0 ]]; then
    echo "ERROR: No source files found in RE_AGENTS_CONFIG.md."
    echo "Ensure the 'All Source Files' list is populated under '## Source Location'."
    exit 1
fi

echo "Found ${#SOURCE_FILES[@]} source files in RE_AGENTS_CONFIG.md."

# Preserve previous checksums so analysis-planner can diff old vs new
if [[ -f "$OUTPUT_FILE" ]]; then
    cp "$OUTPUT_FILE" "$PREV_FILE"
    echo "Previous checksums saved to: artifacts/source_checksums_prev.governance.md"
fi

echo "Computing checksums..."
echo ""

# Write header
cat > "$OUTPUT_FILE" <<EOF
# Source File Checksums

> Auto-generated by scripts/update-checksums.sh on ${DATE}.
> Used by analysis-planner to detect source file changes since the last pipeline run.
> Re-run this script whenever source files are added, modified, or removed.

| File | SHA-256 | Last Updated |
|------|---------|--------------|
EOF

# Compute and write checksums
missing=0
for rel_path in "${SOURCE_FILES[@]}"; do
    abs_path="$REPO_ROOT/$rel_path"
    if [[ ! -f "$abs_path" ]]; then
        echo "  MISSING: $rel_path"
        echo "| $rel_path | MISSING — file not found | $DATE |" >> "$OUTPUT_FILE"
        ((missing++))
        continue
    fi
    checksum=$($SHA_CMD "$abs_path" | awk '{print $1}')
    echo "| $rel_path | $checksum | $DATE |" >> "$OUTPUT_FILE"
    echo "  ✓ $rel_path"
done

echo ""
echo "======================================="
echo "Checksums written to: artifacts/source_checksums.governance.md"

if [[ $missing -gt 0 ]]; then
    echo "WARNING: $missing file(s) listed in RE_AGENTS_CONFIG.md were not found."
    echo "Update RE_AGENTS_CONFIG.md or restore the missing files before running the pipeline."
fi

echo ""
